--liquibase formatted sql

--changeset Seri4:1
CREATE TABLE public.bar
(
    id            bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    address       character varying(255) COLLATE pg_catalog."default",
    average_price double precision,
    description   character varying(255) COLLATE pg_catalog."default",
    image_url     character varying(255) COLLATE pg_catalog."default",
    name          character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT bar_pkey PRIMARY KEY (id)
)

--changeset Seri4:2
CREATE TABLE public.person
(
    id       bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    login    character varying(255) COLLATE pg_catalog."default",
    password character varying(255) COLLATE pg_catalog."default",
    rate     double precision,
    CONSTRAINT person_pkey PRIMARY KEY (id)
)
    TABLESPACE pg_default;

ALTER TABLE public.person
    OWNER to postgres;

--changeset Seri4:3
CREATE TABLE public.event
(
    id          bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    description character varying(255) COLLATE pg_catalog."default",
    image_url   character varying(255) COLLATE pg_catalog."default",
    name        character varying(255) COLLATE pg_catalog."default",
    bar_id      bigint,
    creator_id  bigint,
    CONSTRAINT event_pkey PRIMARY KEY (id),
    CONSTRAINT fkpdw7vfxcaq8glklxwnmoxvic3 FOREIGN KEY (bar_id)
        REFERENCES public.bar (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT fksxghu3f2ci662bfxevwgykxms FOREIGN KEY (creator_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
    TABLESPACE pg_default;

ALTER TABLE public.event
    OWNER to postgres;

--changeset Seri4:4
CREATE TABLE public.event_participant
(
    event_id       bigint NOT NULL,
    participant_id bigint NOT NULL,
    CONSTRAINT uk_c7cdces1jbuunlfvrvk1j6i61 UNIQUE (participant_id),
    CONSTRAINT fk5hxneasi6gucfdlc8690c1ngc FOREIGN KEY (event_id)
        REFERENCES public.event (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID,
    CONSTRAINT fks4wxf7k80jqwv983oogvdk6j9 FOREIGN KEY (participant_id)
        REFERENCES public.person (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
        NOT VALID
)
    TABLESPACE pg_default;

ALTER TABLE public.event_participant
    OWNER to postgres;